//Carl's page

import '@mantine/dates/styles.css';
import '@mantine/charts/styles.css';
import '@mantine/core/styles.css';
import "@/app/globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { ColorSchemeScript, mantineHtmlProps } from '@mantine/core';
import { Metadata } from 'next';
import Providers from '@/components/providers/providers';
import { Toaster } from 'sonner';
import ClientLayout from '@/components/wrappers/client-layout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}